// High resolution QR code generator for export
window.generateHiResQR = async (options) => {
    const { text, size, margin, darkColor, lightColor, errorLevel } = options;

    // Find the preview QR code's DOM element to get its true rendered size
    const previewQR = document.getElementById('qrCode');
    let cssWidth = size, cssHeight = size;
    if (previewQR && previewQR.offsetWidth && previewQR.offsetHeight) {
        cssWidth = previewQR.offsetWidth;
        cssHeight = previewQR.offsetHeight;
    }

    // Create a temporary container for the initial QR code generation
    const tempContainer = document.createElement('div');
    // Define a scaling factor for the high-resolution output.
    // A higher value means more pixels and potentially sharper output for printing/export.
    const scaling = 10; // Generate at 10x the display size for high resolution

    // Calculate the target high-resolution dimensions
    const hiResWidth = cssWidth * scaling;
    const hiResHeight = cssHeight * scaling;

    // Generate the QR code at the target high resolution within the temporary container
    return new Promise((resolve) => {
        new QRCode(tempContainer, {
            text: text,
            width: hiResWidth,
            height: hiResHeight,
            colorDark: darkColor,
            colorLight: lightColor,
            correctLevel: QRCode.CorrectLevel[errorLevel],
            // Adjust margin based on scaling if the library applies margin in pixels
            // If the library's margin is relative, this might not be needed. Test required.
            // margin: margin * scaling, // Example: Scale margin if it's pixel-based
            margin: margin // Assuming library handles margin relative to size or internally
        });

        // Get the canvas generated by the QRCode library
        const sourceCanvas = tempContainer.querySelector('canvas');
        if (!sourceCanvas) {
            // Handle error: QR code canvas not found
            console.error("QR Code canvas element not found in temporary container.");
            resolve({ dataUrl: null, canvas: null }); // Or reject the promise
            return;
        }

        // Create the final high-resolution canvas
        const hiResCanvas = document.createElement('canvas');
        hiResCanvas.width = hiResWidth;
        hiResCanvas.height = hiResHeight;
        const ctx = hiResCanvas.getContext('2d');

        // Ensure crisp pixels by disabling image smoothing
        ctx.imageSmoothingEnabled = false;
        ctx.mozImageSmoothingEnabled = false;
        ctx.webkitImageSmoothingEnabled = false;
        ctx.msImageSmoothingEnabled = false;

        // Draw the generated QR code canvas onto the final high-resolution canvas.
        // Since both canvases are the same size now, this is a direct copy.
        ctx.drawImage(sourceCanvas, 0, 0);

        // Optional: Set CSS styles if this canvas might be displayed directly,
        // scaled down to fit layout. The dataURL will still be high-res.
        hiResCanvas.style.width = cssWidth + 'px'; // Display size
        hiResCanvas.style.height = cssHeight + 'px'; // Display size
        hiResCanvas.style.maxWidth = '100%';
        hiResCanvas.style.maxHeight = '100%';
        hiResCanvas.style.display = 'block';
        hiResCanvas.style.margin = '0 auto';

        // Resolve with the data URL of the high-resolution canvas
        resolve({
            dataUrl: hiResCanvas.toDataURL(), // This will be a large image data URL
            canvas: hiResCanvas // The high-resolution canvas element
        });
    });
};